* Encoding: UTF-8.


GET DATA  /TYPE=TXT
  /FILE="Microdato_Censo2017-Urbano.csv"
  /ENCODING='UTF8'
  /DELCASE=LINE
  /DELIMITERS=";"
  /QUALIFIER='"' 
  /ARRANGEMENT=DELIMITED
  /FIRSTCASE=2
  /IMPORTCASE=ALL
  /VARIABLES=
  REGION F9.0
  PROVINCIA F9.0
  COMUNA F9.0
  DC F9.0
  AREA F9.0
  ZONA F9.0
  NOM_URBANO A120
  CAT F9.0
  REGION_15R F9.0
  PROVINCIA_15R F9.0
  COMUNA_15R F9.0.
CACHE.
EXECUTE.
DATASET NAME Microdato_Censo2017_Urbano WINDOW=FRONT.
